//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online
{
    using System;
    using System.Collections.Generic;
    
    public partial class YourAmount
    {
        public double YourAmount1 { get; set; }
        public int AmountId { get; set; }
        public string Id { get; set; }
        public int ImageId { get; set; }
    }
}
